type: object
description: |-
  Specifies the details of a security config.
  
x-akamai:
  file-path: schemas/configs-get.yaml
additionalProperties: false
required:
- configurations
properties:
  configurations:
    type: array
    description: |
      A list of security configurations.
    items:
      $ref: config-get.yaml
