name: configId
in: path
description: |-
  A unique identifier for each configuration.
  
x-akamai:
  file-path: parameters/config-id-path.yaml
required: true
schema:
  type: integer
  example: 77653
  format: int64
