x-akamai:
  file-path: paths/config-malware-policies.yaml
  path-info: /configs/{configId}/versions/{versionNumber}/malware-policies
parameters:
- $ref: ../parameters/config-id-path.yaml
- $ref: ../parameters/version-number-path.yaml
post:
  operationId: post-malware-policies
  summary: Create a malware policy
  tags:
  - 'Shared resources: Malware policies'
  description: |
    Create a new malware policy for a security configuration version.
  requestBody:
    required: true
    content:
      application/json:
        example:
          $ref: ../examples/malware-policy-post.json
        schema:
          $ref: ../schemas/malware-policy.yaml
  responses:
    201:
      description: |
        Successfully created a malware policy.
      headers:
        Location:
          $ref: ../headers/location.yaml
      content:
        application/json:
          example:
            $ref: ../examples/malware-policy-200.json
          schema:
            $ref: ../schemas/malware-policy.yaml
    400:
      $ref: ../errors/400.yaml
    403:
      description: |
        [Forbidden](ref:403). You don't have access to malware policies in this security configuration.
      $ref: ../errors/403.yaml
    404:
      description: |
        [Not found](ref:404). Security configuration version wasn't found.
      $ref: ../errors/404.yaml
get:
  operationId: get-malware-policies
  summary: List malware policies
  tags:
  - 'Shared resources: Malware policies'
  description: |
    Return malware policies for a security configuration version. _Products:_ All.
  responses:
    200:
      description: |
        Successfully returned the malware policies.
      content:
        application/json:
          example:
            $ref: ../examples/malware-policies-200.json
          schema:
            $ref: ../schemas/malware-policies.yaml
    403:
      description: |
        [Forbidden](ref:403). You don't have access to the malware policy in this security configuration.
      $ref: ../errors/403.yaml
    404:
      description: |
        [Not found](ref:404). The security configuration version wasn't found.
      $ref: ../errors/404.yaml
