x-akamai:
  file-path: paths/config-malware-policy.yaml
  path-info: /configs/{configId}/versions/{versionNumber}/malware-policies/{malwarePolicyId}
parameters:
- $ref: ../parameters/config-id-path.yaml
- $ref: ../parameters/version-number-path.yaml
- $ref: ../parameters/malware-policy-id-path.yaml
get:
  operationId: get-malware-policy
  summary: Get a malware policy
  tags:
  - 'Shared resources: Malware policies'
  description: |
    Return a malware policy. _Products:_ All.
  responses:
    200:
      description: |
        Successfully returned the malware policy.
      content:
        application/json:
          example:
            $ref: ../examples/malware-policy-200.json
          schema:
            $ref: ../schemas/malware-policy.yaml
    403:
      description: |
        [Forbidden](ref:403). You don't have access to this malware policy.
      $ref: ../errors/403.yaml
    404:
      description: |
        [Not found](ref:404). The security configuration version or malware policy wasn't found.
      $ref: ../errors/404.yaml
put:
  operationId: put-malware-policy
  summary: Modify a malware policy
  tags:
  - 'Shared resources: Malware policies'
  description: |
    Update details for a malware policy.
  requestBody:
    required: true
    content:
      application/json:
        example:
          $ref: ../examples/malware-policy-put.json
        schema:
          $ref: ../schemas/malware-policy.yaml
  responses:
    200:
      description: |
        Successfully updated the malware policy.
      content:
        application/json:
          example:
            $ref: ../examples/malware-policy-200.json
          schema:
            $ref: ../schemas/malware-policy.yaml
    400:
      $ref: ../errors/400.yaml
    403:
      description: |
        [Forbidden](ref:403). You don't have access to this malware policy.
      $ref: ../errors/403.yaml
    404:
      description: |
        [Not found](ref:404). The security configuration version or malware policy wasn't found.
      $ref: ../errors/404.yaml
delete:
  operationId: delete-malware-policy
  summary: Remove a malware policy
  tags:
  - 'Shared resources: Malware policies'
  description: |
    Delete a specific malware policy that's not actively in use. To delete an active malware policy, first activate an older configuration version or create a new version without the policy in place. _Products:_ All.
  responses:
    204:
      description: |
        Successfully deleted the malware policy.
    403:
      description: |
        [Forbidden](ref:403). You don't have access to this malware policy.
      $ref: ../errors/403.yaml
    404:
      description: |
        [Not found](ref:404). The security configuration version or malware policy wasn't found.
      $ref: ../errors/404.yaml
